version: 1.3.{build}
image: Visual Studio 2019
before_build:
  - git clone -q --branch=master https://github.com/Amebis/eduEx.git ..\eduEx
  - nuget restore -Verbosity quiet
configuration:
  - Debug
  - Release
platform:
  - x86
  - x64
build:
  project: eduOpenVPN.sln
  parallel: true
  verbosity: minimal
artifacts:
  - path: bin\$(configuration)\$(platform)\eduOpenVPN.dll
  - path: bin\$(configuration)\$(platform)\eduOpenVPN.pdb
  - path: bin\$(configuration)\$(platform)\ar\eduOpenVPN.resources.dll
  - path: bin\$(configuration)\$(platform)\de\eduOpenVPN.resources.dll
  - path: bin\$(configuration)\$(platform)\fr\eduOpenVPN.resources.dll
  - path: bin\$(configuration)\$(platform)\nl\eduOpenVPN.resources.dll
  - path: bin\$(configuration)\$(platform)\sl\eduOpenVPN.resources.dll
  - path: bin\$(configuration)\$(platform)\uk\eduOpenVPN.resources.dll
