version: 1.10.{build}
image: Visual Studio 2019
before_build:
  - git clone -q --branch=master https://github.com/Amebis/eduEx.git ..\eduEx
  - nuget restore -Verbosity quiet
configuration:
  - Debug
  - Release
platform:
  - Any CPU
  - x86
  - x64
build:
  project: eduOpenVPN.sln
  parallel: true
  verbosity: minimal
artifacts:
  - path: bin\$(configuration)\$(platform)
